version: '3.3'

services:
  isis-frontend:
    container_name: isis-frontend
    image: willsem/isis-frontend
    ports:
      - '80:80'
    depends_on:
      - postgres
    networks:
      - isis-net

  isis-backend:
    container_name: isis-backend
    image: willsem/isis-backend
    ports:
      - '5000:80'
    depends_on:
      - postgres
    networks:
      - isis-net

  postgres:
    container_name: isis-postgres
    image: library/postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    restart: always
    networks:
      - isis-net

  pgadmin:
    container_name: isis-pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pg.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - isis-net

volumes:
  postgres-data:
  pgadmin-data:

networks:
  isis-net:
