name: backend

on: push

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
  - name: Setup .NET Core SDK 5.0.x
    uses: actions/setup-dotnet@v1.7.2
  - name: Restore
    run: dotnet restore
  - name: Build
    run: dotnet publish ./backend -c Release -o out
