name: 'Backend CD'

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'Publsh backend'
    needs: 'Build backend'
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: 'Download binary backend'
        uses: actions/download-artifact@v2
        with:
          name: backend-bin

      - name: 'Check Out Repo'
        uses: actions/checkout@v2

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'Build and push'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/isis-backend:latest
