name: backend

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build backend
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.202'
      - run: dotnet restore ./backend
      - run: dotnet publish ./backend -c Release -o out
