name: 'CI CD'

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build backend'
    steps:
      - name: 'Check Out Repo'
        uses: actions/checkout@v2

      - name: 'Build backend project'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.202'
      - run: dotnet restore ./backend
      - run: dotnet publish ./backend -c Release -o ./backend/out

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: backend-bin
          path: ./backend/out
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    name: 'Publsh backend'
    needs: build
    steps:
      - name: 'Check Out Repo'
        uses: actions/checkout@v2

      - name: 'Download binary backend'
        uses: actions/download-artifact@v2
        with:
          name: backend-bin
          path: ./backend/out

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'Build and push'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/isis-backend:latest
