name: 'CI CD'

on: [push, pull_request]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    name: 'Test frontend'
    steps:
      - name: 'Check Out Repo'
        uses: actions/checkout@v2

      - name: 'Setup node'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Install packages'
        run: |
          cd frontend
          npm i

      - name: 'Test frontend project'
        run: |
          cd frontend
          npm test

  build-frontend:
    runs-on: ubuntu-latest
    name: 'Build frontend'
    steps:
      - name: 'Check Out Repo'
        uses: actions/checkout@v2

      - name: 'Setup node'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Install packages'
        run: |
          cd frontend
          npm i

      - name: 'Build frontend project'
        run: |
          cd frontend
          npm run ng build

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: frontend-bin
          path: ./frontend/dist
          retention-days: 1

  publish-frontend:
    runs-on: ubuntu-latest
    name: 'Publish frontend'
    needs: [test-frontend, build-frontend]
    # if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    steps:
      - name: 'Check Out Repo'
        uses: actions/checkout@v2

      - name: 'Download binary backend'
        uses: actions/download-artifact@v2
        with:
          name: frontend-bin
          path: ./frontend/dist

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'Build and push'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/isis-frontend:latest

  test-backend:
    runs-on: ubuntu-latest
    name: 'Test backend'
    steps:
      - name: 'Check Out Repo'
        uses: actions/checkout@v2

      - name: 'Test backend project'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.202'
      - run: dotnet test ./backend

  build-backend:
    runs-on: ubuntu-latest
    name: 'Build backend'
    steps:
      - name: 'Check Out Repo'
        uses: actions/checkout@v2

      - name: 'Build backend project'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.202'
      - run: dotnet restore ./backend
      - run: dotnet publish ./backend -c Release -o ./backend/out

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: backend-bin
          path: ./backend/out
          retention-days: 1

  publish-backend:
    runs-on: ubuntu-latest
    name: 'Publish backend'
    needs: [test-backend, build-backend]
    # if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    steps:
      - name: 'Check Out Repo'
        uses: actions/checkout@v2

      - name: 'Download binary backend'
        uses: actions/download-artifact@v2
        with:
          name: backend-bin
          path: ./backend/out

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'Build and push'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/isis-backend:latest

  deploy:
    runs-on: ubuntu-latest
    name: 'Deploy project'
    needs: [publish-frontend, publish-backend]
    # if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    steps:
      - name: 'Check Out Repo'
        uses: actions/checkout@v2

      - name: 'Configure SSH'
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/staging.key
          sudo chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $REMOTE_HOST
            User $REMOTE_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END

      - name: 'Stop the server'
        run: ssh staging 'docker-compose down'

      - name: 'Remove images'
        run: |
          ssh staging 'docker image rm $(docker image ls -aq)'

      - name: 'Run the server'
        run: ssh staging 'docker-compose up -d'
